  # 应用服务 WEB 访问端口
server:
  port: 8022

  # 连接数据库需要的配置
spring:
  datasource:
    username: root
    password: zhj123
    url: jdbc:mysql://localhost:3306/empmanagement?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  resources:
  ##    配置静态资源访问的路径 (index.html的文件是默认直接作为首页访问的)  [classpath:/static/HTML/ ]
  #    static-locations: [classpath:/templates/ ]

  #  mvc:
  #    配置静态资源访问的路径前缀,对动态资源没有用，动态资源只看@RequestMapping("/***")里面的路径
  #    static-path-pattern: /res/**

  #指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:/Mapper/*.xml



